title: REACH Bytes
url: ""
favicon: /images/favicon.ico
colors:
  primary-color: "#0DB14B"
  secondary-color: "#F47920"
  media-colors:
    - title: media-color-one
      color: "#14c8cf"
    - title: media-color-two
      color: "#e81933"
    - title: media-color-three
      color: "#744d9f"
    - title: media-color-four
      color: "#ffbc00"
    - title: media-color-five
      color: "#00838f"
resources_name: example-resource
description: An Isomer site of the Singapore Government
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://mci-reach-staging.netlify.app
prod: https://mci-reach-prod.netlify.app
